### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by boalove** [Tyilo/insert_dylib#1]
I use the code, and insert libtt_i386.dylib into a App(Mindjet MindManager), which is installed already.
Then run it from the launchpad. It return the following errors:
 " Library not loaded: libtt_i386.dylib
  Referenced from: /Applications/Mindjet MindManager.app/Contents/MacOS/Mindjet MindManager
  Reason: image not found"

I know what the error means --- cannot find libtt_i386.dylib in its search path.
I try the run it from the path of libtt_i386.dylib in terminal, the libtt_i386.dylib will be loaded successfully, I do it as following:
cd path/to/libtt_i386.dylib
lldb /Application/Mindjet MindManager.app

I wanna know if there is a way to fix this problem.

thank you very much.

**Comment by boalove** [comment]
And my email is boalove1314@qq.com, thank you very much.

**Comment by Tyilo** [comment]
Have you tried using the absolute path to the library?
Something like:
```
$ insert_dylib "/path/to/libtt_i386.dylib" "/Applications/Mindjet MindManager.app/Contents/MacOS/Mindjet MindManager"
```

**Comment by boalove** [comment]
it doesn't work.
I guess that run it in the terminal will add the local path to the environment variable.
Then it loads the *.dylib successfully.
you can use "otool -L executable" to see all dylib to be loaded.

I will try other ways.
Thanks a lot!

**Comment by Tyilo** [comment]
Are you sure you didn't insert the .dylib into the already patched binary?
Try running the command I gave you in the previous comment on the non-patched binary.

**Comment by boalove** [comment]
I am sorry replying so late. I tried the command you said again, and finally it works.
and I don't know why "it doesn't work" as I last commented.
Thank you very much. It's so kind of you:)

**Comment by Tyilo** [comment]
No problem.
