### ISSUE TITLE
Supporting ARM64

### ISSUE THREAD

**Issue by trueToastedCode** [tyilo/insert_dylib#11]
Yes, I found the other arm64 issue #10..., but this isn't the same thing. The other repository claims, that ARM64 would actually still work, but I did not came to the same conclusion.

**Issue**
```
./test_patched
zsh: killed     ./test_patched
```

**Reproduce**
```
$ cat > test.c
int main(void) {
	printf("Testing\n");
	return 0;
}
^D
$ clang test.c -o test &> /dev/null
$ insert_dylib /usr/lib/libfoo.dylib test
The provided dylib path doesn't exist. Continue anyway? [y/n] y
Added LC_LOAD_DYLIB to test_patched
$ ./test
Testing
$ ./test_patched
zsh: killed     ./test_patched
```

**Interesting**
I've opened the Terminal with Rosetta enabled, so that it is X86_64 and redone the steps... and it works!
```
$ ./test_patched 
dyld[72520]: Library not loaded: /usr/lib/libfoo.dylib
  Referenced from: <9513973B-B8E3-3A8D-93FE-A40EEF7CDD2B> /Users/lennard/Desktop/insert_dylib/insert_dylib/test_patched
  Reason: tried: '/usr/lib/libfoo.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libfoo.dylib' (no such file), '/usr/lib/libfoo.dylib' (no such file, not in dyld cache), '/usr/local/lib/libfoo.dylib' (no such file)
zsh: abort      ./test_patched
```

**Conclusion**
ARM64 seems to be broken. It would be 🔥, if we could fix this amazing tool for ARM64. Especially, since Apple doesn't even build Intel anymore but this tool being used till this day. However I will probably not be able to do it myself 🥲

**Comment by tyilo** [comment]
Have you tried using a dylib that actually exists?

**Comment by trueToastedCode** [comment]
> Have you tried using a dylib that actually exists?

Thanks for the suggestion... I've tried now, without success.
```
$ cat > example.c
#include <stdio.h>

void hello_dylib() {
    printf("Hello from dylib!\n");
}
^D
$ clang -shared -o example.dylib example.c 
$ insert_dylib /Users/lennard/Desktop/insert_dylib/insert_dylib/example.dylib test
LC_CODE_SIGNATURE load command found. Remove it? [y/n] ← doesn't matter (tried n and y)
$ ./test_patched
zsh: killed     ./test_patched
```

**Comment by trueToastedCode** [comment]
> Have you tried using a dylib that actually exists?

Seems like, this rather is a signing issue... however just choosing `y` for `LC_CODE_SIGNATURE load command found. Remove it? [y/n]` doesn't do the job.

**Comment by trueToastedCode** [comment]
> > Have you tried using a dylib that actually exists?
> 
> Seems like, this is a signing issue... however just choosing `y` for `LC_CODE_SIGNATURE load command found. Remove it? [y/n]` doesn't do the job.

Ok, so MacOS actually requires codesigning nowadays... we can't remove the singing...

**Comment by trueToastedCode** [comment]
> > > Have you tried using a dylib that actually exists?
> > 
> > 
> > Seems like, this is a signing issue... however just choosing `y` for `LC_CODE_SIGNATURE load command found. Remove it? [y/n]` doesn't do the job.
> 
> Ok, so MacOS on arm64 actually requires codesigning nowadays... we can't just remove the signing...

`codesign -f -s - --timestamp=none --all-architectures test_patched`

Depending on the dylib... you may need to do more stuff... like including entitlements... here is an example for the Parallels Desktop crack
```
chflags -R 0 <path>
chown root:wheel <path>
chmod 755 <path>
codesign -f -s - --timestamp=none --all-architectures --entitlements <ent_path> <path>
```
