### ISSUE TITLE
Unable to run my app after inserting a dylib.

### ISSUE THREAD

**Issue by euroboy** [Tyilo/insert_dylib#4]
After inserting a dylib to my app's binary, I cannot run it, XCode gives me the following error message:

![error](https://user-images.githubusercontent.com/6330272/27832592-e13ca728-60d7-11e7-8179-01dd88f59ea1.png)

**Comment by Tyilo** [comment]
What happens if you run the app from the command line?

**Comment by euroboy** [comment]
@Tyilo Sorry, but how exactly to do that, using xcodebuild?

**Comment by euroboy** [comment]
I fixed the issue by enabling Audio Background Mode in Capabilities, but it gives me another error on run:
`dyld: Library not loaded: /Users/me/.../myLib.dylib
  Referenced from: /var/containers/Bundle/Application/.../TestDylib.app/TestDylib
  Reason: image not found`

**Comment by Tyilo** [comment]
No idea
