### ISSUE TITLE
Trying to load .dylib into iOS binary - crash at exec

### ISSUE THREAD

**Issue by arthurdapaz** [Tyilo/insert_dylib#5]
I insert the dylib correctly (I guess), my _otool -L binary_ show me this:

> @executable_path/final.dylib (compatibility version 0.0.0, current version 0.0.0)

Watching my iPad syslog on Xcode after side loading the modified app, I get the following message:

> Aug 15 04:44:53 arthurpad ReportCrash[5619] <Error>: Dyld Error Message:
> 
> Dyld Message: Library not loaded: @executable_path/final.dylib
> 
> Referenced from: /var/containers/Bundle/Application/ABC2F509-0738-44C6-BF1E-E082ED13A460/NvwaStone.app/NvwaStone
> 
> Reason: unsafe use of @executable_path in /var/containers/Bundle/Application/ABC2F509-0738-44C6-BF1E-E082ED13A460/NvwaStone.app/NvwaStone with restricted binary
> 
> Dyld Version: 390.7
> 
> Aug 15 04:44:53 arthurpad SpringBoard[197] <Warning>: Application '(null)' exited for an unknown reason.

What am I doing wrong? Any tips? 😰

**Comment by Tyilo** [comment]
I think you can't use relative dylib paths if the binary is a setuid binary. You must use an absolute path.
